# Notes: all timestamps have :00 appended to the end.
# This means that ending time 0:05 is actually 0:05:00
# and will end before any frame beginning with 0:05:
# TODO: automatically remove any solid color frames from the start and end of each clip.
data = [
    ['Ippon seoi nage', ['Single-handed shoulder throw'], [
        ['https://www.youtube.com/watch?v=FQnOlCxo4oI', ['0:04-0:08',
                                                         '0:09-0:16',
                                                         '0:17-0:20',
                                                         '0:21-0:24',
                                                         '0:26-0:29',
                                                         '0:30-0:38',
                                                         '0:40-0:44',
                                                         '0:45-0:53']],
        ['https://www.youtube.com/watch?v=Au1M9JSXRw8', ['2:39-2:45',
                                                         '3:01-3:05']],
    ]],
    ['Kata guruma', ['Shoulder wheel'], [
        ['https://www.youtube.com/watch?v=cnHRhSy8yi4', ['0:04-0:08',
                                                         '0:09-0:20',
                                                         '0:22-0:26',
                                                         '0:28-0:33',
                                                         '0:35-0:39',
                                                         '0:40-0:51',
                                                         '0:56-0:59',
                                                         '1:01-1:09']],
        ['https://www.youtube.com/watch?v=6tSOm33R6VA', ['2:04-2:10',
                                                         '2:33-2:44']],
    ]],
    ['Kibisu gaeshi', ['One-hand reversal', 'heel-trip reversal'], [
        ['https://www.youtube.com/watch?v=tJylJYfBliA', ['0:04-0:07',
                                                         '0:08-0:13',
                                                         '0:14-0:18',
                                                         '0:19-0:24',
                                                         '0:25-0:28',
                                                         '0:29-0:38',
                                                         '0:39-0:43',
                                                         '0:44-0:52']],
        ['https://www.youtube.com/watch?v=3LLBrF4w86Q', ['0:03-0:06',
                                                         '0:07-0:11']],
    ]],
    ['Morote gari', ['double leg takedown', 'Two-handed reap'], [
        ['https://www.youtube.com/watch?v=BHLQS4K85bs', ['0:04-0:09',
                                                         '0:10-0:14',
                                                         '0:15-0:18',
                                                         '0:19-0:24',
                                                         '0:25-0:28',
                                                         '0:29-0:34']],
    ]],
    ['Obi otoshi', ['Belt drop'], [
        ['https://www.youtube.com/watch?v=ff8U2TVZIYI', ['0:05-0:11',
                                                         '0:12-0:22',
                                                         '0:24-0:27',
                                                         '0:29-0:39',
                                                         '0:42-0:48',
                                                         '0:50-1:02']],
    ]],
    ['Seoi nage', ['Shoulder throw'], [
        ['https://www.youtube.com/watch?v=zIq0xI0ogxk', ['0:05-0:08',
                                                         '0:09-0:13',
                                                         '0:14-0:17',
                                                         '0:18-0:26',
                                                         '0:27-0:30',
                                                         '0:31-0:40',
                                                         '0:42-0:45',
                                                         '0:46-0:51',
                                                         '0:52-0:55',
                                                         '0:56-1:04',
                                                         '1:06-1:09',
                                                         '1:11-1:19']],
    ]],
    ['Seoi otoshi', ['Shoulder drop'], [
        ['https://www.youtube.com/watch?v=vu1TMVNnq34', ['0:05-0:07',
                                                         '0:09-0:16',
                                                         '0:18-0:21',
                                                         '0:22-0:26',
                                                         '0:28-0:31',
                                                         '0:33-0:38',
                                                         '0:39-0:41',
                                                         '0:42-0:51',
                                                         '0:52-0:56',
                                                         '0:57-1:02',
                                                         '1:04-1:08',
                                                         '1:09-1:19']],
    ]],
    ['Sukui nage', ['Scoop throw'], [
        ['https://www.youtube.com/watch?v=vU6aJ2kFxoI', ['0:04-0:08',
                                                         '0:10-0:17',
                                                         '0:18-0:21',
                                                         '0:23-0:29',
                                                         '0:31-0:35',
                                                         '0:37-0:49',
                                                         '0:51-0:54',
                                                         '0:55-1:06',
                                                         '1:07-1:10',
                                                         '1:12-1:17',
                                                         '1:18-1:22',
                                                         '1:23-1:28',
                                                         '1:29-1:33',
                                                         '1:34-1:45']],
    ]],
    ['Sumi otoshi', ['Corner drop'], [
        ['https://www.youtube.com/watch?v=lLU9wv52ni0', ['0:04-0:08',
                                                         '0:09-0:14',
                                                         '0:16-0:19',
                                                         '0:20-0:32',
                                                         '0:33-0:36',
                                                         '0:38-0:44',
                                                         '0:45-0:51']],
    ]],
    ['Tai otoshi', ['Body drop'], [
        ['https://www.youtube.com/watch?v=4x6S3Q-Ktv8', ['0:04-0:08',
                                                         '0:09-0:13',
                                                         '0:14-0:17',
                                                         '0:18-0:25',
                                                         '0:26-0:29',
                                                         '0:30-0:40',
                                                         '0:41-0:43',
                                                         '0:44-0:50',
                                                         '0:51-0:55',
                                                         '0:57-1:01',
                                                         '1:03-1:06',
                                                         '1:08-1:14']],
    ]],
    ['Uchi mata sukashi', ['Inner thigh void throw'], [
        ['https://www.youtube.com/watch?v=V-RS3uhtVWM', ['0:04-0:08',
                                                         '0:09-0:13',
                                                         '0:14-0:18',
                                                         '0:19-0:25',
                                                         '0:26-0:31',
                                                         '0:32-0:35',
                                                         '0:36-0:41',
                                                         '0:42-0:45',
                                                         '0:46-0:50']],
    ]],
    ['Uki otoshi', ['Floating drop'], [
        ['https://www.youtube.com/watch?v=6H5tmncOY4Q', ['0:04-0:08',
                                                         '0:09-0:17',
                                                         '0:18-0:21',
                                                         '0:23-0:29',
                                                         '0:30-0:37',
                                                         '0:39-0:42',
                                                         '0:43-0:48',
                                                         '0:49-0:55']],
    ]],
    ['Yama arashi', ['Mountain storm'], [
        ['https://www.youtube.com/watch?v=MGlyKmSuzdc', ['0:04-0:08',
                                                         '0:09-0:22',
                                                         '0:23-0:27',
                                                         '0:28-0:34',
                                                         '0:35-0:40',
                                                         '0:41-0:46',
                                                         '0:47-0:50',
                                                         '0:51-1:00',
                                                         '1:01-1:05',
                                                         '1:06-1:12']],
    ]],
    ['Kouchi gaeshi', ['Small inner reap reversal'], [
        ['https://www.youtube.com/watch?v=_MWAdYi_LC4', ['0:04-0:07',
                                                         '0:08-0:16',
                                                         '0:17-0:20',
                                                         '0:21-0:25',
                                                         '0:26-0:29',
                                                         '0:30-0:36',
                                                         '0:37-0:41',
                                                         '0:42-0:47',
                                                         '0:48-0:51',
                                                         '0:52-0:57',
                                                         '0:58-1:01',
                                                         '1:02-1:07',
                                                         '1:08-1:12',
                                                         '1:13-1:20',
                                                         '1:22-1:25',
                                                         '1:26-1:34']],
    ]],
    ['Kuchiki taoshi', ['Single leg takedown'], [
        ['https://www.youtube.com/watch?v=ZNL47q1aJNY', ['0:04-0:08',
                                                         '0:09-0:15',
                                                         '0:16-0:20',
                                                         '0:21-0:25',
                                                         '0:26-0:29',
                                                         '0:31-0:41',
                                                         '0:42-0:46',
                                                         '0:48-0:58']],
    ]],
]

for name, aliases, examples in data:
    print(name)
    print(aliases)
    for url, timecodes in examples:
        print(url)
        # TODO: ensure the video is downloaded
        for timecode in timecodes:
            start, end = timecode.split('-')
            print(f'  {start}-{end}')
            # TODO: crop the video to remove watermarks and other junk
            # TODO: use ffmpeg to slice the video
