# Notes: all timestamps have :00 appended to the end.
# This means that ending time 0:05 is actually 0:05:00
# and will end before any frame beginning with 0:05:
# TODO: automatically remove any solid color frames from the start and end of each clip.
data = [
    # Te-waza: hand throwing techniques
    ['Ippon seoi nage', '一本背負投', ['Single-handed shoulder throw'], [
        ['https://www.youtube.com/watch?v=FQnOlCxo4oI', ['0:04-0:08',
                                                         '0:09-0:16',
                                                         '0:17-0:20',
                                                         '0:21-0:24',
                                                         '0:26-0:29',
                                                         '0:30-0:38',
                                                         '0:40-0:44',
                                                         '0:45-0:53']],
        ['https://www.youtube.com/watch?v=Au1M9JSXRw8', ['2:39-2:45',
                                                         '3:01-3:05']],
    ]],
    ['Kata guruma', '肩車', ['Shoulder wheel'], [
        ['https://www.youtube.com/watch?v=cnHRhSy8yi4', ['0:04-0:08',
                                                         '0:09-0:20',
                                                         '0:22-0:26',
                                                         '0:28-0:33',
                                                         '0:35-0:39',
                                                         '0:40-0:51',
                                                         '0:56-0:59',
                                                         '1:01-1:09']],
        ['https://www.youtube.com/watch?v=6tSOm33R6VA', ['2:04-2:10',
                                                         '2:33-2:44']],
    ]],
    ['Kibisu gaeshi', '踵返', ['One-hand reversal', 'heel-trip reversal'], [
        ['https://www.youtube.com/watch?v=tJylJYfBliA', ['0:04-0:07',
                                                         '0:08-0:13',
                                                         '0:14-0:18',
                                                         '0:19-0:24',
                                                         '0:25-0:28',
                                                         '0:29-0:38',
                                                         '0:39-0:43',
                                                         '0:44-0:52']],
        ['https://www.youtube.com/watch?v=3LLBrF4w86Q', ['0:03-0:06',
                                                         '0:07-0:11']],
    ]],
    ['Morote gari', '双手刈', ['double leg takedown', 'Two-handed reap'], [
        ['https://www.youtube.com/watch?v=BHLQS4K85bs', ['0:04-0:09',
                                                         '0:10-0:14',
                                                         '0:15-0:18',
                                                         '0:19-0:24',
                                                         '0:25-0:28',
                                                         '0:29-0:34']],
    ]],
    ['Obi otoshi', '帯落', ['Belt drop'], [
        ['https://www.youtube.com/watch?v=ff8U2TVZIYI', ['0:05-0:11',
                                                         '0:12-0:22',
                                                         '0:24-0:27',
                                                         '0:29-0:39',
                                                         '0:42-0:48',
                                                         '0:50-1:02']],
    ]],
    ['Seoi nage', '背負投', ['Shoulder throw'], [
        ['https://www.youtube.com/watch?v=zIq0xI0ogxk', ['0:05-0:08',
                                                         '0:09-0:13',
                                                         '0:14-0:17',
                                                         '0:18-0:26',
                                                         '0:27-0:30',
                                                         '0:31-0:40',
                                                         '0:42-0:45',
                                                         '0:46-0:51',
                                                         '0:52-0:55',
                                                         '0:56-1:04',
                                                         '1:06-1:09',
                                                         '1:11-1:19']],
    ]],
    ['Seoi otoshi', '背負落', ['Shoulder drop'], [
        ['https://www.youtube.com/watch?v=vu1TMVNnq34', ['0:05-0:07',
                                                         '0:09-0:16',
                                                         '0:18-0:21',
                                                         '0:22-0:26',
                                                         '0:28-0:31',
                                                         '0:33-0:38',
                                                         '0:39-0:41',
                                                         '0:42-0:51',
                                                         '0:52-0:56',
                                                         '0:57-1:02',
                                                         '1:04-1:08',
                                                         '1:09-1:19']],
    ]],
    ['Sukui nage', '掬投', ['Scoop throw'], [
        ['https://www.youtube.com/watch?v=vU6aJ2kFxoI', ['0:04-0:08',
                                                         '0:10-0:17',
                                                         '0:18-0:21',
                                                         '0:23-0:29',
                                                         '0:31-0:35',
                                                         '0:37-0:49',
                                                         '0:51-0:54',
                                                         '0:55-1:06',
                                                         '1:07-1:10',
                                                         '1:12-1:17',
                                                         '1:18-1:22',
                                                         '1:23-1:28',
                                                         '1:29-1:33',
                                                         '1:34-1:45']],
    ]],
    ['Sumi otoshi', '隅落', ['Corner drop'], [
        ['https://www.youtube.com/watch?v=lLU9wv52ni0', ['0:04-0:08',
                                                         '0:09-0:14',
                                                         '0:16-0:19',
                                                         '0:20-0:32',
                                                         '0:33-0:36',
                                                         '0:38-0:44',
                                                         '0:45-0:51']],
    ]],
    ['Tai otoshi', '体落', ['Body drop'], [
        ['https://www.youtube.com/watch?v=4x6S3Q-Ktv8', ['0:04-0:08',
                                                         '0:09-0:13',
                                                         '0:14-0:17',
                                                         '0:18-0:25',
                                                         '0:26-0:29',
                                                         '0:30-0:40',
                                                         '0:41-0:43',
                                                         '0:44-0:50',
                                                         '0:51-0:55',
                                                         '0:57-1:01',
                                                         '1:03-1:06',
                                                         '1:08-1:14']],
    ]],
    ['Uchi mata sukashi', '内股透', ['Inner thigh void throw'], [
        ['https://www.youtube.com/watch?v=V-RS3uhtVWM', ['0:04-0:08',
                                                         '0:09-0:13',
                                                         '0:14-0:18',
                                                         '0:19-0:25',
                                                         '0:26-0:31',
                                                         '0:32-0:35',
                                                         '0:36-0:41',
                                                         '0:42-0:45',
                                                         '0:46-0:50']],
    ]],
    ['Uki otoshi', '浮落', ['Floating drop'], [
        ['https://www.youtube.com/watch?v=6H5tmncOY4Q', ['0:04-0:08',
                                                         '0:09-0:17',
                                                         '0:18-0:21',
                                                         '0:23-0:29',
                                                         '0:30-0:37',
                                                         '0:39-0:42',
                                                         '0:43-0:48',
                                                         '0:49-0:55']],
    ]],
    ['Yama arashi', '山嵐', ['Mountain storm'], [
        ['https://www.youtube.com/watch?v=MGlyKmSuzdc', ['0:04-0:08',
                                                         '0:09-0:22',
                                                         '0:23-0:27',
                                                         '0:28-0:34',
                                                         '0:35-0:40',
                                                         '0:41-0:46',
                                                         '0:47-0:50',
                                                         '0:51-1:00',
                                                         '1:01-1:05',
                                                         '1:06-1:12']],
    ]],
    ['Kouchi gaeshi', '小内返', ['Small inner reap reversal'], [
        ['https://www.youtube.com/watch?v=_MWAdYi_LC4', ['0:04-0:07',
                                                         '0:08-0:16',
                                                         '0:17-0:20',
                                                         '0:21-0:25',
                                                         '0:26-0:29',
                                                         '0:30-0:36',
                                                         '0:37-0:41',
                                                         '0:42-0:47',
                                                         '0:48-0:51',
                                                         '0:52-0:57',
                                                         '0:58-1:01',
                                                         '1:02-1:07',
                                                         '1:08-1:12',
                                                         '1:13-1:20',
                                                         '1:22-1:25',
                                                         '1:26-1:34']],
    ]],
    ['Kuchiki taoshi', '朽木倒', ['Single leg takedown'], [
        ['https://www.youtube.com/watch?v=ZNL47q1aJNY', ['0:04-0:08',
                                                         '0:09-0:15',
                                                         '0:16-0:20',
                                                         '0:21-0:25',
                                                         '0:26-0:29',
                                                         '0:31-0:41',
                                                         '0:42-0:46',
                                                         '0:48-0:58']],
    ]],

    # Koshi-waza: hip throwing techniques
    ['Hane goshi', '跳腰', ['Spring hip throw'], [
        ['https://www.youtube.com/watch?v=M9_7De6A1kk', ['0:04-0:07',
                                                         '0:08-0:18',
                                                         '0:19-0:23',
                                                         '0:24-0:29',
                                                         '0:31-0:34',
                                                         '0:35-0:40',
                                                         '0:41-0:44',
                                                         '0:45-0:50',
                                                         '0:51-0:55',
                                                         '0:56-1:01',
                                                         '1:02-1:06',
                                                         '1:07-1:16']],
    ]],
    ['Harai goshi', '払腰', ['Sweeping hip throw'], [
        ['https://www.youtube.com/watch?v=qTo8HlAAkOo', ['0:04-0:08',
                                                         '0:10-0:15',
                                                         '0:16-0:19',
                                                         '0:21-0:25',
                                                         '0:26-0:30',
                                                         '0:30-0:34',
                                                         '0:35-0:39',
                                                         '0:40-0:49',
                                                         '0:50-0:54',
                                                         '0:55-1:00',
                                                         '1:01-1:05',
                                                         '1:06-1:11']],
    ]],
    ['Koshi guruma', '腰車', ['Hip wheel'], [
        ['https://www.youtube.com/watch?v=SU7Id6uVJ44', ['0:04-0:08',
                                                         '0:09-0:13',
                                                         '0:14-0:17',
                                                         '0:18-0:24',
                                                         '0:25-0:29',
                                                         '0:30-0:37',
                                                         '0:38-0:41',
                                                         '0:42-0:46',
                                                         '0:47-0:51',
                                                         '0:52-0:58',
                                                         '0:59-1:03',
                                                         '1:04-1:09']],
    ]],
    ['O goshi', '大腰', ['Full hip throw'], [
        ['https://www.youtube.com/watch?v=yhu1mfy2vJ4', ['0:05-0:08',
                                                         '0:09-0:16',
                                                         '0:18-0:22',
                                                         '0:23-0:31',
                                                         '0:32-0:36',
                                                         '0:37-0:47',
                                                         '0:48-0:51',
                                                         '0:53-0:58',
                                                         '1:00-1:03',
                                                         '1:05-1:10',
                                                         '1:11-1:14',
                                                         '1:15-1:25']],
    ]],
    ['Sode tsurikomi goshi', '袖釣込腰', ['Sleeve lifting and pulling hip throw'], [
        ['https://www.youtube.com/watch?v=QsmAxpmYLOI', ['0:04-0:09',
                                                         '0:10-0:22',
                                                         '0:23-0:28',
                                                         '0:29-0:35',
                                                         '0:36-0:40',
                                                         '0:41-0:51',
                                                         '0:52-0:56',
                                                         '0:57-1:04',
                                                         '1:05-1:08',
                                                         '1:10-1:16',
                                                         '1:17-1:21',
                                                         '1:22-1:36']],
    ]],
    ['Tsuri goshi', '釣腰', ['Lifting hip throw'], [
        ['https://www.youtube.com/watch?v=51Htlp7xEvE', ['0:04-0:09',
                                                         '0:10-0:17',
                                                         '0:18-0:22',
                                                         '0:23-0:30',
                                                         '0:31-0:35',
                                                         '0:36-0:42',
                                                         '0:43-0:47',
                                                         '0:48-0:56',
                                                         '0:57-1:00',
                                                         '1:01-1:06',
                                                         '1:07-1:10',
                                                         '1:11-1:19',
                                                         '1:20-1:23',
                                                         '1:24-1:29',
                                                         '1:31-1:34',
                                                         '1:35-1:41']],
    ]],
    ['Tsurikomi goshi', '釣込腰', ['Lifting and pulling hip throw'], [
        ['https://www.youtube.com/watch?v=McfzA0yRVt4', ['0:04-0:08',
                                                         '0:09-0:18',
                                                         '0:19-0:22',
                                                         '0:23-0:30',
                                                         '0:31-0:36',
                                                         '0:37-0:42',
                                                         '0:43-0:48',
                                                         '0:49-0:54',
                                                         '0:55-0:59',
                                                         '1:00-1:12',
                                                         '1:14-1:18',
                                                         '1:20-1:28']],
    ]],
    ['Uki goshi', '浮腰', ['Floating half-hip throw'], [
        ['https://www.youtube.com/watch?v=bPKwtB4lyOQ', ['0:05-0:08',
                                                         '0:10-0:17',
                                                         '0:18-0:21',
                                                         '0:23-0:29',
                                                         '0:30-0:34',
                                                         '0:35-0:40',
                                                         '0:42-0:45',
                                                         '0:46-0:51']],
    ]],
    ['Ushiro goshi', '後腰', ['Rear throw'], [
        ['https://www.youtube.com/watch?v=ORIYstuxYT8', ['0:05-0:09',
                                                         '0:10-0:15',
                                                         '0:16-0:20',
                                                         '0:21-0:32',
                                                         '0:34-0:38',
                                                         '0:39-0:44',
                                                         '0:45-0:49',
                                                         '0:51-1:03']],
    ]],
    ['Utsuri goshi', '移腰', ['Hip shift'], [
        ['https://www.youtube.com/watch?v=4pQd_bEnlf0', ['0:04-0:08',
                                                         '0:10-0:15',
                                                         '0:16-0:21',
                                                         '0:23-0:29',
                                                         '0:31-0:34',
                                                         '0:35-0:41',
                                                         '0:42-0:46',
                                                         '0:47-0:58']],
    ]],

    # Ashi-waza: foot throwing techniques
    ['Ashi guruma', '足車', ['Leg wheel'], [
        ['https://www.youtube.com/watch?v=ROeayhvom9U', ['0:05-0:08',
                                                         '0:09-0:14',
                                                         '0:16-0:19',
                                                         '0:20-0:30',
                                                         '0:32-0:35',
                                                         '0:36-0:41',
                                                         '0:42-0:45',
                                                         '0:46-0:56']],
    ]],
    ['De Ashi Harai', '出足払', ['Advanced foot sweep'], [
        ['https://www.youtube.com/watch?v=4BUUvqxi_Kk', ['0:05-0:08',
                                                         '0:10-0:13',
                                                         '0:15-0:21',
                                                         '0:22-0:25',
                                                         '0:26-0:30',
                                                         '0:31-0:38',
                                                         '0:39-0:42',
                                                         '0:43-0:48',
                                                         '0:49-0:57',
                                                         '0:58-1:01',
                                                         '1:02-1:07',
                                                         '1:08-1:17']],
    ]],
    ['Hane goshi gaeshi', '跳腰返', ['Hip spring counter'], [
        ['https://www.youtube.com/watch?v=9bZAZSBtnGs', ['0:05-0:09',
                                                         '0:10-0:19',
                                                         '0:20-0:24',
                                                         '0:25-0:30',
                                                         '0:31-0:35',
                                                         '0:36-0:41']],
    ]],
    ['Harai goshi gaeshi', '払腰返', ['Hip sweep counter'], [
        ['https://www.youtube.com/watch?v=4U3It-7PPsc', ['0:05-0:09',
                                                         '0:10-0:16',
                                                         '0:17-0:21',
                                                         '0:22-0:27',
                                                         '0:28-0:32',
                                                         '0:33-0:41']],
    ]],
    ['Harai tsurikomi ashi', '払釣込足', ['Lift-pull foot sweep'], [
        ['https://www.youtube.com/watch?v=gGPXvWL8VbE', ['0:05-0:09',
                                                         '0:10-0:15',
                                                         '0:17-0:27',
                                                         '0:29-0:32',
                                                         '0:33-0:37',
                                                         '0:38-0:49',
                                                         '0:50-0:53',
                                                         '0:55-1:07',
                                                         '1:09-1:13',
                                                         '1:14-1:20',
                                                         '1:22-1:33']],
    ]],
    ['Hiza guruma', '膝車', ['Knee wheel'], [
        ['https://www.youtube.com/watch?v=JPJx9-oAVns', ['0:05-0:08',
                                                         '0:10-0:15',
                                                         '0:16-0:24',
                                                         '0:25-0:28',
                                                         '0:30-0:34',
                                                         '0:35-0:42',
                                                         '0:44-0:47',
                                                         '0:48-0:54',
                                                         '0:55-1:02',
                                                         '1:03-1:06',
                                                         '1:08-1:13',
                                                         '1:14-1:25']],
    ]],
    ['Kosoto gake', '小外掛', ['Small outer hook'], [
        ['https://www.youtube.com/watch?v=8b6kY4s4zH4', ['0:05-0:09',
                                                         '0:10-0:15',
                                                         '0:16-0:27',
                                                         '0:28-0:31',
                                                         '0:32-0:37',
                                                         '0:38-0:46',
                                                         '0:47-0:50',
                                                         '0:52-0:57',
                                                         '0:59-1:10',
                                                         '1:12-1:15',
                                                         '1:16-1:21',
                                                         '1:22-1:33']],
    ]],
    ['Kosoto gari', '小外刈', ['Small outer reap'], [
        ['https://www.youtube.com/watch?v=jeQ541ScLB4', ['0:05-0:09',
                                                         '0:11-0:16',
                                                         '0:17-0:20',
                                                         '0:21-0:31',
                                                         '0:33-0:36',
                                                         '0:38-0:42',
                                                         '0:43-0:45',
                                                         '0:47-0:56']],
    ]],
    ['Kouchi gari', '小内刈', ['Small inner reap'], [
        ['https://www.youtube.com/watch?v=3Jb3tZvr9Ng', ['0:05-0:10',
                                                         '0:12-0:18',
                                                         '0:20-0:23',
                                                         '0:25-0:31',
                                                         '0:33-0:36',
                                                         '0:38-0:44',
                                                         '0:48-0:50',
                                                         '0:52-0:59',
                                                         '1:01-1:03',
                                                         '1:05-1:13',
                                                         '1:15-1:18',
                                                         '1:20-1:31']],
    ]],
    ['O guruma', '大車', ['Large wheel'], [
        ['https://www.youtube.com/watch?v=SnZciTAY9vc', ['0:05-0:07',
                                                         '0:09-0:14',
                                                         '0:15-0:18',
                                                         '0:20-0:31',
                                                         '0:33-0:36',
                                                         '0:38-0:43',
                                                         '0:44-0:48',
                                                         '0:49-0:59']],
    ]],
    ['Okuri Ashi Harai', '送足払', ['Sliding foot sweep'], [
        ['https://www.youtube.com/watch?v=nw1ZdRjrdRI', ['0:05-0:09',
                                                         '0:10-0:21',
                                                         '0:23-0:26',
                                                         '0:27-0:36',
                                                         '0:38-0:41',
                                                         '0:42-0:47',
                                                         '0:49-0:51',
                                                         '0:54-0:57',
                                                         '0:59-1:02',
                                                         '1:03-1:11',
                                                         '1:13-1:16',
                                                         '1:17-1:28',
                                                         '1:31-1:35',
                                                         '1:36-1:46',
                                                         '1:48-1:51',
                                                         '1:53-1:58']],
    ]],
    ['Osoto gaeshi', '大外返', ['Big outer reap counter'], [
        ['https://www.youtube.com/watch?v=8ZjM3X_EANo', ['0:05-0:09',
                                                         '0:10-0:16',
                                                         '0:17-0:19',
                                                         '0:20-0:28',
                                                         '0:29-0:32',
                                                         '0:33-0:39',
                                                         '0:40-0:43',
                                                         '0:45-0:54',
                                                         '0:55-0:58',
                                                         '0:59-1:13']],
    ]],
    ['Osoto gari', '大外刈', ['Big outer reap'], [
        ['https://www.youtube.com/watch?v=c-A_nP7mKAc', ['0:06-0:10',
                                                         '0:12-0:17',
                                                         '0:19-0:23',
                                                         '0:24-0:35',
                                                         '0:37-0:41',
                                                         '0:42-0:48',
                                                         '0:49-0:53',
                                                         '0:55-1:05',
                                                         '1:07-1:12',
                                                         '1:13-1:22',
                                                         '1:23-1:28',
                                                         '1:30-1:44']],
    ]],
    ['Osoto guruma', '大外車', ['Big outer wheel'], [
        ['https://www.youtube.com/watch?v=92KbCm6pQeI', ['0:05-0:09',
                                                         '0:10-0:17',
                                                         '0:19-0:22',
                                                         '0:23-0:28',
                                                         '0:30-0:34',
                                                         '0:35-0:41',
                                                         '0:43-0:47',
                                                         '0:48-1:00']],
    ]],
    ['Osoto otoshi', '大外落', ['Big outer drop'], [
        ['https://www.youtube.com/watch?v=2DsVvDw7b8g', ['0:06-0:09',
                                                         '0:10-0:16',
                                                         '0:17-0:20',
                                                         '0:22-0:29',
                                                         '0:31-0:35',
                                                         '0:36-0:46',
                                                         '0:47-0:51',
                                                         '0:52-1:03']],
    ]],
    ['Ouchi gaeshi', '大内返', ['Big inner reap counter'], [
        ['https://www.youtube.com/watch?v=dCyZTXyjIXE', ['0:06-0:08',
                                                         '0:09-0:16',
                                                         '0:17-0:19',
                                                         '0:20-0:23',
                                                         '0:28-0:32',
                                                         '0:33-0:36',
                                                         '0:37-0:44',
                                                         '0:45-0:47',
                                                         '0:48-0:52',
                                                         '0:53-0:55',
                                                         '0:56-1:01']],
    ]],
    ['Ouchi gari', '大内刈', ['Big inner reap'], [
        ['https://www.youtube.com/watch?v=0itJFhV9pDQ', ['0:05-0:09',
                                                         '0:11-0:19',
                                                         '0:21-0:25',
                                                         '0:26-0:31',
                                                         '0:32-0:35',
                                                         '0:37-0:42',
                                                         '0:44-0:47',
                                                         '0:48-0:56',
                                                         '0:58-1:01',
                                                         '1:03-1:09',
                                                         '1:11-1:14',
                                                         '1:15-1:27']],
    ]],
    ['Sasae tsurikomi ashi', '支釣込足', ['Propping and drawing ankle throw'], [
        ['https://www.youtube.com/watch?v=699i--pvYmE', ['0:06-0:09',
                                                         '0:11-0:14',
                                                         '0:16-0:19',
                                                         '0:20-0:26',
                                                         '0:27-0:29',
                                                         '0:31-0:38',
                                                         '0:39-0:42',
                                                         '0:43-0:51',
                                                         '0:53-0:56',
                                                         '0:58-1:03',
                                                         '1:04-1:13']],
    ]],
    ['Tsubame gaeshi', '燕返', ['Swallow counter'], [
        ['https://www.youtube.com/watch?v=GwweWqqFB5g', ['0:06-0:08',
                                                         '0:09-0:15',
                                                         '0:19-0:22',
                                                         '0:23-0:25',
                                                         '0:26-0:29',
                                                         '0:30-0:32',
                                                         '0:33-0:39',
                                                         '0:41-0:43',
                                                         '0:44-0:51',
                                                         '0:52-1:03']],
    ]],
    ['Uchi mata', '内股', ['Inner-thigh'], [
        ['https://www.youtube.com/watch?v=iUpSu5J-bgw', ['0:05-0:09',
                                                         '0:10-0:17',
                                                         '0:18-0:22',
                                                         '0:23-0:29',
                                                         '0:31-0:35',
                                                         '0:37-0:48',
                                                         '0:50-0:53',
                                                         '0:55-1:01',
                                                         '1:02-1:06',
                                                         '1:08-1:16',
                                                         '1:18-1:33',
                                                         '1:34-1:38',
                                                         '1:39-1:50']],
    ]],
    ['Uchi mata gaeshi', '内股返', ['Inner-thigh counter'], [
        ['https://www.youtube.com/watch?v=Sy6sLWxkWYw', ['0:05-0:08',
                                                         '0:09-0:19',
                                                         '0:20-0:23',
                                                         '0:25-0:31',
                                                         '0:33-0:36',
                                                         '0:37-0:42']],
    ]],

    # Ma-sutemi waza (真捨身技): Rear sacrifice projections
    ['Hikikomi gaeshi', '引込返', 'Pulling in reversal', [
        ['https://www.youtube.com/watch?v=92zUYWBp5N8', ['0:05-0:10',
                                                         '0:11-0:23',
                                                         '0:25-0:29',
                                                         '0:30-0:35',
                                                         '0:36-0:39',
                                                         '0:40-0:46',
                                                         '0:47-0:50',
                                                         '0:51-0:58']],
    ]],
    ['Sumi gaeshi', '隅返', 'Corner reversal', [
        ['https://www.youtube.com/watch?v=5VhduA5xkbA', ['0:06-0:10',
                                                         '0:11-0:21',
                                                         '0:22-0:25',
                                                         '0:27-0:32',
                                                         '0:33-0:37',
                                                         '0:38-0:44',
                                                         '0:46-0:49',
                                                         '0:51-0:59']],
    ]],
    ['Tawara gaeshi', '俵返', 'Rice bag reversal throw', [
        ['https://www.youtube.com/watch?v=TmTWgrmViZc', ['0:06-0:11',
                                                         '0:12-0:20',
                                                         '0:21-0:25',
                                                         '0:26-0:39',
                                                         '0:40-0:43',
                                                         '0:45-0:51',
                                                         '0:52-0:56',
                                                         '0:57-1:04']],
    ]],
    ['Tomoe nage', '巴投', 'Circle throw', [
        ['https://www.youtube.com/watch?v=880WbHvHv6A', ['0:06-0:10',
                                                         '0:11-0:16',
                                                         '0:18-0:21',
                                                         '0:22-0:28',
                                                         '0:30-0:32',
                                                         '0:34-0:44',
                                                         '0:45-0:48',
                                                         '0:49-0:54']],
    ]],
    ['Ura nage', '裏投', 'Rear throw', [
        ['https://www.youtube.com/watch?v=Fgi9b8DJ5sQ', ['0:05-0:10',
                                                         '0:11-0:17',
                                                         '0:18-0:28']],
    ]],

    # Yoko-sutemi waza (橫捨身技): side sacrifice projections
    ['Daki wakare', '抱分', ['High separation'], [
        ['https://www.youtube.com/watch?v=Hr0cOMGBDYo', ['0:05-0:10',
                                                         '0:11-0:24',
                                                         '0:26-0:31',
                                                         '0:32-0:40',
                                                         '0:41-0:47',
                                                         '0:48-0:56',
                                                         '0:57-1:02',
                                                         '1:03-1:12']],
    ]],
    ['Hane makikomi', '跳巻込', ['Springing wraparound'], [
        ['https://www.youtube.com/watch?v=6CRBGLGz9j8', ['0:05-0:09',
                                                         '0:10-0:19',
                                                         '0:21-0:23',
                                                         '0:25-0:35',
                                                         '0:36-0:39',
                                                         '0:40-0:45',
                                                         '0:46-0:49',
                                                         '0:51-0:59']],
    ]],
    ['Harai makikomi', '払巻込', ['Hip sweep wraparound'], [
        ['https://www.youtube.com/watch?v=VBaHzKaCXss', ['0:06-0:09',
                                                         '0:10-0:19',
                                                         '0:20-0:22',
                                                         '0:23-0:28',
                                                         '0:29-0:34',
                                                         '0:35-0:43',
                                                         '0:44-0:48',
                                                         '0:50-1:06']],
    ]],
    ['Kani basami', '蟹挟', ['Crab throw', 'scissors throw'], [
        ['https://www.youtube.com/watch?v=OR-HGHnarYc', ['0:06-0:10',
                                                         '0:11-0:17',
                                                         '0:18-0:27']],
    ]],
    ['Kawazu gake', '河津掛', ['One-leg entanglement'], [
        ['https://www.youtube.com/watch?v=w6G57bWACi0', ['0:06-0:10',
                                                         '0:11-0:17',
                                                         '0:18-0:31']],
    ]],
    ['Osoto makikomi', '大外巻込', ['Big outer wraparound'], [
        ['https://www.youtube.com/watch?v=DGDv2oMwmas', ['0:06-0:10',
                                                         '0:11-0:17',
                                                         '0:19-0:23',
                                                         '0:25-0:38',
                                                         '0:40-0:44',
                                                         '0:46-0:51',
                                                         '0:54-0:59',
                                                         '1:00-1:09']],
    ]],
    ['Soto makikomi', '外巻込', ['Outer wraparound'], [
        ['https://www.youtube.com/watch?v=bWG9O1BVKtQ', ['0:05-0:10',
                                                         '0:11-0:25',
                                                         '0:27-0:32',
                                                         '0:33-0:39',
                                                         '0:40-0:43',
                                                         '0:45-0:57']],
    ]],
    ['Tani otoshi', '谷落', ['Valley drop'], [
        ['https://www.youtube.com/watch?v=3b9Me3Fohpk', ['0:05-0:10',
                                                         '0:11-0:16',
                                                         '0:18-0:22',
                                                         '0:23-0:32',
                                                         '0:33-0:36',
                                                         '0:37-0:42',
                                                         '0:43-0:47',
                                                         '0:48-0:52',
                                                         '0:53-0:56',
                                                         '0:57-1:02',
                                                         '1:03-1:07',
                                                         '1:08-1:17']],
    ]],
    ['Uchi makikomi', '内巻込', ['Inner wraparound'], [
        ['https://www.youtube.com/watch?v=5BowcjduxVc', ['0:06-0:10',
                                                         '0:11-0:17',
                                                         '0:18-0:21',
                                                         '0:22-0:37',
                                                         '0:38-0:42',
                                                         '0:43-0:49',
                                                         '0:51-0:54',
                                                         '0:56-1:06']],
    ]],
    ['Uchi mata makikomi', '内股巻込', ['Inner thigh wraparound'], [
        ['https://www.youtube.com/watch?v=jZXENTLpJCI', ['0:05-0:09',
                                                         '0:10-0:15',
                                                         '0:16-0:20',
                                                         '0:21-0:29',
                                                         '0:31-0:34',
                                                         '0:35-0:39',
                                                         '0:41-0:44',
                                                         '0:45-0:50']],
    ]],
    ['Uki waza', '浮技', ['Floating technique'], [
        ['https://www.youtube.com/watch?v=weVOpJ63gII', ['0:06-0:11',
                                                         '0:12-0:18',
                                                         '0:20-0:24',
                                                         '0:25-0:35',
                                                         '0:37-0:41',
                                                         '0:42-0:49',
                                                         '0:51-0:54',
                                                         '0:56-1:02']],
    ]],
    ['Yoko gake', '横掛', ['Side prop'], [
        ['https://www.youtube.com/watch?v=tP1Sj1uDfSo', ['0:06-0:10',
                                                         '0:11-0:20',
                                                         '0:21-0:25',
                                                         '0:26-0:37',
                                                         '0:38-0:42',
                                                         '0:44-0:51',
                                                         '0:52-0:57',
                                                         '0:58-1:06']],
    ]],
    ['Yoko guruma', '横車', ['Side wheel'], [
        ['https://www.youtube.com/watch?v=MehP6I5cY2c', ['0:06-0:10',
                                                         '0:11-0:24',
                                                         '0:25-0:29',
                                                         '0:31-0:37',
                                                         '0:38-0:42',
                                                         '0:43-0:53',
                                                         '0:55-0:59',
                                                         '1:00-1:11']],
    ]],
    ['Yoko otoshi', '横落', ['Side drop'], [
        ['https://www.youtube.com/watch?v=MnNG67pF_a0', ['0:06-0:10',
                                                         '0:11-0:19',
                                                         '0:21-0:24',
                                                         '0:25-0:32',
                                                         '0:33-0:37',
                                                         '0:38-0:42',
                                                         '0:44-0:46',
                                                         '0:47-0:53']],
    ]],
    ['Yoko wakare', '横分', ['Side separation'], [
        ['https://www.youtube.com/watch?v=bp1tscHlePI', ['0:06-0:11',
                                                         '0:12-0:29',
                                                         '0:31-0:36',
                                                         '0:38-0:48',
                                                         '0:49-0:54',
                                                         '0:58-1:12',
                                                         '1:15-1:20',
                                                         '1:22-1:33']],
    ]],
]

num_examples = 0

for name, jp, aliases, examples in data:
    print(name)
    print(jp)
    print(aliases)
    for url, timecodes in examples:
        print(url)
        # TODO: use OCR to detect watermarks
        # TODO: ensure the video is downloaded
        for timecode in timecodes:
            num_examples += 1
            start, end = timecode.split('-')
            print(f'  {start}-{end}')
            # TODO: detect and remove solid color frames
            # TODO: use ffmpeg to slice the video
            # TODO: also remove watermarks and other junk with ffmpeg
print(f'{len(data)} total techniques')
print(f'{num_examples} total examples')
